name = "riemann"
defaultTargets = ["RiemannCanon"]

[[lean_lib]]
name = "RiemannCanon"

[[lean_lib]]
name = "T8Join"
srcDir = "fixtures/t8w"

[[lean_lib]]
name = "T8c"
srcDir = "fixtures/t8c"

[[lean_lib]]
name = "T8d"
srcDir = "fixtures/t8d"

[[lean_lib]]
name = "T8e"
srcDir = "fixtures/t8e"

[[lean_lib]]
name = "T8f"
srcDir = "fixtures/t8f"

[[lean_lib]]
name = "T8g"
srcDir = "fixtures/t8g"

[[lean_lib]]
name = "T8h"
srcDir = "fixtures/t8h"

[[lean_lib]]
name = "T8i"
srcDir = "fixtures/t8i"

[[lean_lib]]
name = "T8j"
srcDir = "fixtures/t8j"

[[lean_lib]]
name = "T8k"
srcDir = "fixtures/t8k"

[[lean_lib]]
name = "T8l"
srcDir = "fixtures/t8l"

[[lean_lib]]
name = "T8m"
srcDir = "fixtures/t8m"

[[lean_lib]]
name = "Rev1"
srcDir = "fixtures/rev1"

[[lean_lib]]
name = "Rev2"
srcDir = "fixtures/rev2"
