name = "riemann"
defaultTargets = ["RiemannCanon"]

[[lean_lib]]
name = "RiemannCanon"

[[lean_lib]]
name = "T8Join"
srcDir = "t8w"

[[lean_lib]]
name = "T8c"
srcDir = "t8c"

[[lean_lib]]
name = "T8d"
srcDir = "t8d"

[[lean_lib]]
name = "T8e"
srcDir = "t8e"

[[lean_lib]]
name = "T8f"
srcDir = "t8f"

[[lean_lib]]
name = "T8g"
srcDir = "t8g"

[[lean_lib]]
name = "T8h"
srcDir = "t8h"

[[lean_lib]]
name = "T8i"
srcDir = "t8i"

[[lean_lib]]
name = "T8j"
srcDir = "t8j"

[[lean_lib]]
name = "T8k"
srcDir = "t8k"

[[lean_lib]]
name = "T8l"
srcDir = "t8l"

[[lean_lib]]
name = "T8m"
srcDir = "t8m"
